//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De1_NguyenTanSuong_21133078
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vi
    {
        public int MaVi { get; set; }
        public string TenVi { get; set; }
        public Nullable<double> Gia { get; set; }
        public string MauSac { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaHang { get; set; }
    
        public virtual Hang Hang { get; set; }
        public virtual LoaiVi LoaiVi { get; set; }
    }
}
